GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTcyODMxNjcxLCJleHAiOjE1NzI4MzE2ODZ9.E9SEieDDlc6BtHHKn_HGCiq6uYQa06CViXcl-KpKQuQ

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTcyODMxNzk1fQ.kFRNm99G5eLHdVR22QKN_9xKIDxmLdcT5I-9FGBfvwA"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTcyODMxNzk1fQ.kFRNm99G5eLHdVR22QKN_9xKIDxmLdcT5I-9FGBfvwA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bob"
}